
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add your customization settings below this line
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- hpa.yaml

namePrefix: frontend
